friuts = []

f1 = input("Enter a friut Name:")
friuts.append(f1)
f2 = input("Enter a friut Name:")
friuts.append(f2)
f3 = input("Enter a friut Name:")
friuts.append(f3)
f4 = input("Enter a friut Name:")
friuts.append(f4)
f5 = input("Enter a friut Name:")
friuts.append(f5)
f6 = input("Enter a friut Name:")
friuts.append(f6)
f7 = input("Enter a friut Name:")
friuts.append(f7)
print(friuts)